const P = `\n\n🔥 Code MASON10 = 10% off!\n📞 (321) 830-6272 · info@omarsdogtraining.com`;

export function mason(m) {
  const l = m.toLowerCase();
  if (l.match(/slip|lead|leash|collar|gear/)) return `🛍️ ODT Handler Slip Lead — $24.99\n\n3ft braided nylon, brass O-ring, leather stopper. Same lead Omar uses daily.\n\n✓ All breeds & sizes\n✓ FREE how-to video\n✓ 5 colors: Black, Red, Navy, Green, Brown\n\n💰 2 for $39.99 (save $10!)\n🎁 FREE with any training sign-up!${P}`;
  if (l.match(/how to|put on|tutorial|video/)) return `🎬 Slip Lead Tutorial:\n\n1. Thread rope through brass O-ring\n2. Slide loop over dog's head\n3. Position HIGH behind ears — not on throat\n4. Adjust leather stopper — 2 finger gap\n5. Walk with purpose. Pull = tightens. Slack = rewards.\n\n⚠️ Never yank. Gentle pressure only.\n\n📦 Get yours: $24.99${P}`;
  if (l.match(/aggressi|bite|lunge|attack|growl|reactive/)) return `Aggression is our #1 specialty, Handler.\n\n🏆 Behavioral Transformation at AWW — $3,500\n→ 8 sessions + vet checkup + life coaching\n→ 98% success rate\n\nStep 1: Get a 3ft slip lead ($24.99)\nStep 2: Create distance BEFORE reaction\nStep 3: Walk the other way — that's leading${P}`;
  if (l.match(/pull|drag|lunging/)) return `Pulling = your dog thinks THEY'RE leading.\n\nFix: Stop when leash tightens. Plant. Wait for slack. Resume.\n\nGet our 3ft slip lead ($24.99) — short length = handler position.\n\n🏆 Saturday Training: $399 — only 6 spots!${P}`;
  if (l.match(/poop|scoop|waste|yard|clean/)) return `💩 PoopPatrol™\n\n→ Weekly: $14/visit ($60/mo)\n→ 2x/week: $11/visit ($95/mo)\n→ Extra dog: +$2\n→ One-time cleanup: $49\n\n🏆 BUNDLE: PoopPatrol + Walk & Talks = $249/mo (save $10!)\n\nServing ALL Brevard County!${P}`;
  if (l.match(/walk|walking|exercise/)) return `🚶 Walk & Talks™\n\n→ 20 min: $13 · 30 min: $18 · 60 min: $28\n→ 3x/week: $199/mo\n→ 5x/week: $349/mo\n→ Extra dog: +$5\n\nGPS tracking + photos + report every walk!${P}`;
  if (l.match(/price|cost|how much|afford|pay|money/)) return `🐾 Full Menu:\n\n🎓 Saturday Group: $399\n🔥 Behavioral: $3,500\n🎯 Private: $250/session\n🆘 Emergency: $500\n🛍️ Slip Lead: $24.99\n💩 PoopPatrol: from $60/mo\n🚶 Walk & Talks: from $13\n📱 Virtual: $75-199/mo\n⭐ Memberships: $97-1,497/mo\n🐾 Puppy Package: $149\n🧠 Life Coaching: $200/session\n🎁 Gift Cards: any amount\n\nWe accept cards, Zelle, Venmo, Cash App, Apple Pay, crypto!${P}`;
  if (l.match(/book|saturday|class|schedule|enroll/)) return `🗓️ Saturday at AWW:\n\n→ 10:00 AM — Basic Obedience (6 spots)\n→ 12:00 PM — Basic Obedience (6 spots)\n\n$399 for 4 sessions · FREE slip lead included!\n\nTue & Thu classes (6 PM & 8 PM) coming soon!${P}`;
  if (l.match(/member|pack|alpha|elite|subscri/)) return `⭐ Memberships:\n\n🥉 Pack: $97/mo — AI, Q&A, videos, 10% off\n🥇 Alpha: $497/mo — 2 sessions + coaching + direct line ← BEST VALUE!\n💎 Elite: $1,497/mo — UNLIMITED everything\n\nAll members get a FREE slip lead!${P}`;
  if (l.match(/deal|promo|code|discount|coupon|refer|save/)) return `🎁 Active Codes:\n\n→ MASON10 — 10% off first service\n→ PACK50 — $50 off Saturday Training\n→ SOCIAL15 — 15% off (follow + tag us)\n→ SLIPLEAD — FREE lead with training\n→ BUNDLE10 — $10/mo off PoopPatrol + Walks\n→ REFER50 — $50 credit per referral\n→ 🎖️ Military/First Responder: 15% off\n→ 🐕 Multi-dog: 20% off 2nd dog${P}`;
  if (l.match(/puppy|pup|baby|new dog/)) return `🐾 Puppy Welcome Package — $149!\n\n→ 1 private session with Omar\n→ FREE slip lead ($24.99 value)\n→ New Puppy Handler Guide PDF\n→ 1 month Mason AI access\n\nOr join Saturday Training ($399) for group socialization!${P}`;
  if (l.match(/gift/)) return `🎁 Gift Cards — give the gift of transformation!\n\nAvailable in any amount. Perfect for birthdays, holidays, new puppy gifts.\n\nCall (321) 830-6272 or email to purchase.${P}`;
  if (l.match(/military|first responder|teacher|service|vet/)) return `🎖️ 15% off for heroes!\n\nActive military, veterans, first responders, and teachers get 15% off ALL services.\n\nBrevard County = Patrick Space Force Base families. We serve those who serve.${P}`;
  if (l.match(/virtual|video|online|zoom/)) return `📱 Virtual Training:\n\n📞 Quick Call: $75/mo (30 min)\n🎯 Handler Hotline: $125/mo (60 min) ← Most Popular!\n🔥 Unlimited: $199/mo (120 min)\n\nLive video with Omar from anywhere!${P}`;
  if (l.match(/life coach|coaching|personal|leadership/)) return `🧠 Life Coaching — $200/session\n\nThe way you show up for your dog is how you show up in life.\n\n→ Standalone: $200/session (60 min)\n→ Included in Alpha Leader ($497/mo)\n→ Unlimited in Elite Circle ($1,497/mo)${P}`;
  if (l.match(/mason|who are you|help|what can you/)) return `I'm Mason 🐾 — Omar's Belgian Malinois and your 24/7 AI Super Agent!\n\n🎓 Training programs\n🛍️ Slip lead ($24.99)\n💩 PoopPatrol™\n🚶 Walk & Talks™\n💰 Full pricing\n📅 Saturday booking\n🎁 Promo codes & deals\n🧠 Behavioral guidance\n🚨 Emergency escalation to Omar${P}`;
  return `Hey Handler! 🐾 I'm Mason!\n\nTry asking:\n→ "Prices" · "Slip lead" · "PoopPatrol"\n→ "Book Saturday" · "Deals" · "Memberships"\n→ "My dog pulls" · "Puppy package"\n→ "Military discount" · "Gift cards"${P}`;
}